### ISSUE TITLE
[Bug] 마인더 전환 버튼 누를시 시 오류 메시지 발생 

### ISSUE THREAD

**Issue by rmdnps10** [sharemindteam/sharemind-client#161]
## Describtion

<br>
계정 생성 후에 마인더 전환 버튼 눌렀을 때 오류 메시지가 발생

<br>
<img width="472" alt="스크린샷 2024-03-14 오전 11 01 27" src="https://github.com/sharemindteam/sharemind-client/assets/87219998/6f67cc5c-fa6c-4eb8-97a8-235698d24c9d">

## Etc

<br>
추가적인 사항을 작성해주세요.(선택)
<br>

**Comment by leekyuho114** [comment]
백 이슈입니다.
