### ISSUE TITLE
[Feature] 스켈레톤 UI를 구현합니다.

### ISSUE THREAD

**Issue by rmdnps10** [sharemindteam/sharemind-client#179]
## Describtion

<br>
홈 화면에서 진행중인 상담 리스트 밀리는 사용자 경험의 해결을 위해서, 스켈레톤 UI 도입이 필요합니다
<br>

## TodoList

<br>

- [ ] Todo1
- [ ] Todo2

<br>

## Etc

<br>
추가적인 사항을 작성해주세요.(선택)
<br>

**Comment by leekyuho114** [comment]
이거 혹시 구현 시작하셨나용??

**Comment by rmdnps10** [comment]
아니요 맨 나중에 하려고요 ㅎㅎ..
