### ISSUE TITLE
[Bug] 페이지 전환 시 스크롤 맨 위로 올리기

### ISSUE THREAD

**Issue by rmdnps10** [sharemindteam/sharemind-client#195]
## Describtion

<br>
마인더 인증 시에 스크롤 내리고 다음 페이지로 넘어가면 스크롤 맨위로 올려야해요.

`window.scrollTo` 안먹음
<br>
<img width="379" alt="스크린샷 2024-03-28 오후 9 05 58" src="https://github.com/sharemindteam/sharemind-client/assets/87219998/0e865f45-4f7e-40aa-bfa8-c03255abc8b9">

## Etc

<br>
추가적인 사항을 작성해주세요.(선택)
<br>

**Comment by leekyuho114** [comment]
[scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) 사용하면 됩니다!
