### ISSUE TITLE
[Bug] 구매자 상단 검색 UI 깨짐

### ISSUE THREAD

**Issue by rmdnps10** [sharemindteam/sharemind-client#23]
## Describtion

<br>
http://localhost:3000/buyer/search
buyer/search에서 구매자 검색 UI 깨지는데 나만그런가? 왼쪽 화살표

<br>

## Etc

<br>
추가적인 사항을 작성해주세요.(선택)
<br>

**Comment by leekyuho114** [comment]
일단 내꺼에선 괜찮긴한데 어떤식으로 꺠져??
이부분 좀 반응형 구현하다가 이상하게 꼬였을거 같은데..
