### ISSUE TITLE
[Bug] 마인더가 상담 방식에서 편지와 실시간 채팅 중 하나만 선택했을 때 상담료 부문에서 두가지 방식이 모두 뜸

### ISSUE THREAD

**Issue by rmdnps10** [sharemindteam/sharemind-client#240]
## 문제 상황 (AS-IS)

<br>
마인더가 상담 방식 중 편지만 선택했을 때, 편지와 채팅의 상담료 두 개가 모두 뜹니다!
<br>

## 기대상황 (TO-BE)

<br>
마인더가 편지만 선택했을 경우엔 경우엔 편지만, 채팅만 뜨게 해야할 거 같습니다
<br>

## 재현 방법

<br>

<br>

## 스크린샷

(상담 방식으로 편지만 선택한 마인더)
<br>
<img width="371" alt="스크린샷 2024-04-23 오전 5 17 13" src="https://github.com/sharemindteam/sharemind-client/assets/87219998/46fdfef5-a75e-4759-a889-8a9bbe7e33da">

<br>

## 환경

<br>
(어떠한 환경에서 문제가 발생했는지 정보를 입력합니다.)

- **URL(*필수)**: https://www.sharemindapp.com/profile/37
- Email(계정정보): 
- 브라우저:
<br>

**Comment by kyuhho** [comment]
* 들준마 카드, 검색 등등 모두 적용되어야합니다.
slack: https://w1696598846-dky839981.slack.com/archives/C06M1AD8RSN/p1714222303088079
