### ISSUE TITLE
[Bug] 마인더 페이지에 URL경로로 바로 접속했을 때 항상 로그인 페이지로 이동합니다.

### ISSUE THREAD

**Issue by rmdnps10** [sharemindteam/sharemind-client#297]
## 문제 상황 (AS-IS)

<br>
/minder 마인더 경로로 되어있는 페이지들에 URL쳐서 접속하면 토큰 만료여부와 상관없이 토큰을 reissue 하는 api 오류 처리가 되어 로그인 페이지로 이동합니다.
<br>

## 기대상황 (TO-BE)

<br>
쿠키에 유효한 토큰이 있을 경우에는 URL 경로를 통해 마인더 페이지로 이동했을 때 로그인 페이지로 이동하지 않아야 합니다.
<br>

## 재현 방법

<br>
지금 배포된 도메인 (https://www.sharemindapp.com/) 에서는 일어나지 않는 문제인 거 같고, 개발 브랜치에서 벌어지는 문제인거같네요!
<br>

## 스크린샷

<br>
(문제상황을 빠르게 이해할 수 있도록 참고할 수 있는 UI 스크린샷을 첨부합니다.)

https://github.com/sharemindteam/sharemind-client/assets/87219998/ae127a9a-30a8-4b06-9ebb-95173d6e949f

<br>

## 환경

<br>
(어떠한 환경에서 문제가 발생했는지 정보를 입력합니다.)

- **URL(*필수)**: 
- Email(계정정보):
- 브라우저: 
<br>

**Comment by kyuhho** [comment]
setCookie path 넘기도록 수정?

**Comment by kyuhho** [comment]
현재 재현되지 않기 때문에 일단 close하겠습니다.
